AWSTemplateFormatVersion: "2010-09-09"
Description: "(SA0019) - aws-fleet-predictive-maintenance
  Predictive Maintenance for Fleets of Vehicles.
  Version 1"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Solution Configuration"
        Parameters:
          - S3BucketName
          - SolutionPrefix
      -
        Label:
          default: "Advanced Configuration"
        Parameters:
          - SageMakerNotebookInstanceType
          - LaunchSageMakerNotebookClassic

    ParameterLabels:
      S3BucketName:
        default: "S3 bucket to be created for the solution. Note: Bucket name will be prefixed with sm-soln-"
      SolutionPrefix:
        default: "Solution Resources Name Prefix"
      SageMakerNotebookInstanceType:
        default: "SageMaker Notebook Instance Type"
      LaunchSageMakerNotebookClassic:
        default: Launch SageMaker Notebook Instance
Parameters:
  SolutionPrefix:
    Type: String
    Default: "sm-soln-fleet-predict"
    Description: |
      Used to name resources created as part of this stack (and inside nested stacks too).
      Can be the same as the stack name used by AWS CloudFormation, but this field has extra
      constraints because it's used to name resources with restrictions (e.g. Amazon S3 bucket
      names cannot contain capital letters).
    AllowedPattern: '^sm-soln-fleet-predict[a-z0-9\-]{0,20}$'
    ConstraintDescription: |
      Only allowed to use lowercase letters, hyphens and/or numbers.
      Should also start with 'sm-soln-fleet-predict' for permission management.
  IamRole:
    Type: String
    Default: ""
    Description: |
      IAM Role that will be attached to the resources created by this CloudFormation to grant them permissions to
      perform their required functions. This role should allow SageMaker and Lambda perform the required actions like
      creating training jobs and processing jobs. If left blank, the template will attempt to create a role for you.
      This can cause a stack creation error if you don't have privileges to create new roles.
  S3BucketName:
    Description: Amazon S3 Bucket used to store datasets and models.
    Type: String
  SageMakerNotebookInstanceType:
    Description: SageMaker notebook instance type.
    Type: String
    Default: "ml.t3.medium"
  LaunchSageMakerNotebookClassic:
    Description: Whether to launch classic sagemaker notebook instance
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"
Conditions:
  CreateClassicSageMakerResources: !Equals [ !Ref LaunchSageMakerNotebookClassic, "Yes" ]
  CreateCustomSolutionRole: !Equals [!Ref IamRole, ""]
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: "Retain"
    Properties:
      BucketName: !Sub "${SolutionPrefix}-${S3BucketName}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          -
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: Avoids user having to manually create an Amazon S3 bucket for logs.
          - id: W51
            reason: Current default access policy is sufficient.

  PermissionsStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: CreateCustomSolutionRole
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/sagemaker-solutions-${AWS::Region}/aws-fleet-predictive-maintenance/cloudformation/aws-fleet-predictive-maintenance-permissions.yaml"
      Parameters:
        SolutionPrefix: !Ref SolutionPrefix
        S3BucketName: !Ref S3BucketName

  SageMakerStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: CreateClassicSageMakerResources
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/sagemaker-solutions-${AWS::Region}/aws-fleet-predictive-maintenance/cloudformation/aws-fleet-predictive-maintenance-sagemaker.yaml"
      Parameters:
        SolutionPrefix: !Ref SolutionPrefix
        S3BucketName: !Ref S3Bucket
        SageMakerRoleArn: !If [CreateCustomSolutionRole, !GetAtt PermissionsStack.Outputs.SageMakerRoleArn, !Ref IamRole]
        SageMakerNotebookInstanceType: !Ref SageMakerNotebookInstanceType

Outputs:
  NotebookInstance:
    Condition: CreateClassicSageMakerResources
    Description: "SageMaker Notebook instance to manually orchestrate data preprocessing and model training"
    Value: !GetAtt SageMakerStack.Outputs.NotebookInstance

  SageMakerIamRole:
    Description: "SageMaker Execution Role for the Solution"
    Value: !If [CreateCustomSolutionRole, !GetAtt PermissionsStack.Outputs.SageMakerRoleArn, !Ref IamRole]
